[package]
name = "neurokaraoke-desktop"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "abort"

[dependencies]
tokio = { version = "1.53.1", features = ["full"]}
eframe = "0.35.0"
egui_extras = { version = "*", features = ["image", "http"] }
image = { version = "0.25", features = ["png"] }
rodio = { version = "0.22.2", default-features = false, features = ["playback", "mp3"] }
url = "2.5.8"
uuid = "1.24.0"
reqwest = "0.13.4"
rand = "0.9"

neurokaraoke-metadata-client = { path = "./neurokaraoke-metadata-mirror/sdk/rust" }